'use strict';

// WE WRITE ARRAYS MANUALLY IN TWO WAYS:
// THROUGH SIMPLE MAKING A ARRAY OF NUMBERS DIRECTLY OR CALLING A CONSTRUCTOR.
const arr = [1, 2, 3, 4, 5, 6, 7];
console.log(arr);
// WE CAN USE ARRAY CONTRUCTOR FUNCTION.
console.log(new Array(1, 2, 3, 4, 5, 6, 7));

// WE CAN DEFINE OR GENERATE ARRAYS PROGRAMATICALLY , WITHOUT TO PUTTING THEM THE VALUE.

// THE FIRST METHOD OF CREATING ARRAY PROGRAMATICALLY:
const x = new Array(7);
// IT WILL CREATE AN ARRAY , OF 7 EMPTY ELEMENTS.
console.log(x); // [ EMPTY * 7 ]
// WE CAN'T USE MAP METHOD TO FILL IT.
console.log(x.map(() => 5)); // [ EMPTY * 7 ]
// INSTEAD THERE IS A METHOD CALLED FILL METHOD , WHICH CAN FILL THE ENTIRE ARRAY.
// THE ARRAY WILL FILLED WITH 7 ELEMENTS.
// IT IS LIKE SPLICE METHOD AS WE CAN SPECIFY THE ELEMENT AS WELL.
// IT ALSO MUTATES THE ORIGINAL ARRAY.
x.fill(1);
console.log(x); //[ 1 , 1 , 1 , 1 , 1 , 1 , 1 ]
// WE CAN SPECIFY ELEMET:
x.fill(2, 3); // PUT 2'S STARTS FROM THE 3RD INDEX.
console.log(x);
// IT ALSO WORKS FOR OTHER ARRAYS AS WELL.

// THE SECOND METHOD OF CREATING ARRAY PROGRAMATICALLY

// THE NICER WAY OF CREATING ARRAYS.
// WHAT IF WE ACTUALLY WANTED TO RECREATE AN ENTIRE ARRAY PROGRAMMATICALLY . THE ABOVE arr ARRAY:
// FOR THAT , WE CAN USE THE ARRAY.FROM FUNCTION.
// HERE , THE ARRAY IS CONSTRUCTOR FUNCTION OBJECT , AND THE FROM IS METHOD OF THIS FUNCTION OBJECT.
const y = Array.from({ length: 19 }, () => 4);
// IT WILL CREATE AN ARRAY WITH THE LENGTH 19 AND THE CALLBACK FUNCTION IS USED FOR FILLING THAT ARRAY WITH THE GIVEN NUMBER.
console.log(y);

const z = Array.from({ length: 12 }, (_, index) => index + 1);
// WE USED THE _ IN PLACE OF ELEMENT , BECAUSE WE DON'T NEED IT , AND IT IS A CONVENTION TO USE _ IF WE DON'T NEED , WE HAVE TO DEFINE BECAUSE THE ORDER IN WHICH THEY ARE PLACED.
console.log(z);

// CREATING ARRAYS PROGRAMATICALLY ARE VERY USEFUL
// WE CAN CREATE AN ARRAY WITH 100 RANDOM DICE ROLLS:
// USING ARRAY.FROM METHOD:
const diceRolls = Array.from({ length: 100 }, () =>
  Math.trunc(Math.random() * 6)
);
console.log(diceRolls);

// THE ARRAY.FROM FUNCTION WAS INITIALLY INTRODUCED INTO JAVASCRIPT , IN ORDER TO CREATE ARRAYS FROM ARRAYS LIKE STRUCTURES.
// STRINGS , MAPS , SETS , THEY ARE ALL ITERABLES IN JAVASCRIPT.
// THEY CAN BE CONVERTED TO REAL ARRAYS USING ARRAY.FROM.
// THE NAME ITSELF MEANS THAT WE CAN CREATE ARRAYS FROM OTHER THINGS.

// BESIDES THESE ITERABLES ,THERE IS ANOTHER ARRAYS LIKE STRUCTURE WHICH IS QUERYSELECTORALL().
// IT RETURNS A NODE LIST WHICH IS SOMETHING LIKE AN ARRAY, WHICH CONTAIN ALL THE SELECTED ELEMENTS BUT IT'S NOT A REAL ARRAY. SO IT DOES'T HAVE METHODS LIKE MAP .
// SO IT DOESN'T HAVE THE
